template_path: loadbalancer.py
parameters:
    albname: sceptredemo
    subnet1:
        - !stack_output dev/subnets.yaml::PublicSubnet1
    subnet2:
        - !stack_output dev/subnets.yaml::PublicSubnet2
    vpcid:
        - !stack_output dev/vpc.yaml::VPC